//! Conformance pin for the #126 toolchain gap (A): a String-SCANNING `spec fn`
//! whose `&String` param is read via `byte_at`/`len` MUST lower correctly and
//! certify L3, and a fn that NAMES it in a contract MUST certify L3 too.
//!
//! THE GAP (root cause in `fluffy-lower/src/lower.rs`): the exec `lower_fn`
//! signature path threads a fn's `&String` params via `.with_strings(..)`, so an
//! exec `byte_at(i)` rewrites to the spec accessor + coerces correctly. But the
//! `spec fn` body path (`lower_spec_fn_body` / `lower_spec_fn_body_with_schemes`)
//! and the `decreases` measure (`spec_dec`) did NOT thread the spec fn's `&String`
//! params — so a `&String`-param `byte_at(i)` in a spec-fn body did NOT rewrite to
//! `spec_byte_at(i as int)` (it hit the `usize`-typed exec accessor → E0308:
//! `usize` vs `int`), and a `dec s.len()` left the exec `len` in spec position
//! (poisoning the measure's type inference). Two further narrowings were needed for
//! the String-scanning recursion to type-check under Verus's UNBOUNDED-`int` spec
//! arithmetic: a recursive arg `i + 1` is `(i + 1) as u64` and a contract `s.len()`
//! arg is `s.spec_len() as u64` (a user spec fn's surface integer param is `u64`).
//! The byte-view `s.data@` rewrite was ALSO gated so a `&String`-param spec fn's
//! self-call passes `s` (a `&TString` reference) through, NOT `s.data@` (a
//! `Seq<u8>` — for the GENERATED byte-view fns only).
//!
//! This test is the regression pin so (A) cannot silently regress: it drives the
//! built `forge` binary's certificate ladder (real verus — the EXTERNAL cert
//! oracle the toolchain does not author for itself) over a `spec fn` that scans a
//! `&String` param with `byte_at`, plus an exec twin + a fn naming it in a
//! contract; all three must certify L3. The negative arm pins non-vacuity: a
//! mutated exec body (return the loose constant `acc`-seed `0`) breaks the
//! `ens result == <spec fn>` equality and rejects below L3 (R-DEFER-9).
//!
//! The verus check SKIPS LOUDLY when verus is absent (the `editor_runs.rs`
//! precedent) — never panic on a missing solver (R-CODE-4). `tests/` is not
//! anti-pattern-gated, so `unwrap`/`expect`/`panic!` are fine here (R-APG-2).
//!
//! R-CHAR-3: the expected level is the design authority — L3 == a fully-discharged
//! real-verus proof (`fluffy-design.md` §6 ladder semantics;
//! `.design/basis/07-strings.md` REQ-4, the `spec_byte_at(i as int)` spec
//! accessor) — NOT copied from the toolchain's own output. The negative L0 is the
//! divergence the gap produced.

use std::path::{Path, PathBuf};
use std::process::Command;

use serde_json::Value;

fn forge_bin() -> PathBuf {
    PathBuf::from(env!("CARGO_BIN_EXE_forge"))
}

/// `true` iff verus is reachable (mirrors `editor_runs.rs`). SKIP LOUDLY otherwise
/// — a missing solver is never a test failure (R-CODE-4).
fn verus_present() -> bool {
    if let Ok(p) = std::env::var("VERUS_BIN") {
        if Path::new(&p).exists() {
            return true;
        }
    }
    if let Ok(out) = Command::new("which").arg("verus").output() {
        if out.status.success() && !String::from_utf8_lossy(&out.stdout).trim().is_empty() {
            return true;
        }
    }
    if let Ok(home) = std::env::var("HOME") {
        if PathBuf::from(home).join(".local/bin/verus").exists() {
            return true;
        }
    }
    false
}

/// Write a throwaway `.th` fixture under the temp dir, `forge check --json` it,
/// remove it, and return the parsed cert array.
fn check_program(tag: &str, program: &str) -> Vec<Value> {
    let fixture = std::env::temp_dir().join(format!(
        "forge_spec_str_param_{tag}_{}.th",
        std::process::id()
    ));
    std::fs::write(&fixture, program).expect("write fixture");
    let out = Command::new(forge_bin())
        .arg("check")
        .arg(&fixture)
        .arg("--json")
        .output()
        .expect("spawn forge check");
    let _ = std::fs::remove_file(&fixture);
    let stdout = String::from_utf8_lossy(&out.stdout);
    serde_json::from_str::<Value>(stdout.trim())
        .unwrap_or_else(|e| {
            panic!(
                "[{tag}] forge check --json stdout must be one JSON doc: {e}\nstdout:\n{stdout}\nstderr:\n{}",
                String::from_utf8_lossy(&out.stderr)
            )
        })
        .as_array()
        .unwrap_or_else(|| panic!("[{tag}] forge check --json must emit an array of certs"))
        .clone()
}

fn level_of(certs: &[Value], item: &str) -> String {
    certs
        .iter()
        .find(|c| c.get("item").and_then(|v| v.as_str()) == Some(item))
        .unwrap_or_else(|| panic!("no cert for `{item}` in {certs:#?}"))["level"]
        .as_str()
        .unwrap_or_else(|| panic!("cert for `{item}` has no string level"))
        .to_string()
}

/// A String-scanning `spec fn` (`byte_at`/`len` over a `&String` param, a recursive
/// `\n`-scan with a `dec` measure), its exec twin, and a fn naming the spec fn in a
/// contract. The byte tested is `120` (`'x'`) so the test does not collide with the
/// editor's `10` (`\n`); the SHAPE is the #126 `spec_line_start` twin.
const SCAN_PROGRAM: &str = "\
spec fn spec_scan(s: &String, i: u64, target: u64, acc: u64) -> u64
  dec target - i
{
  if i >= target {
    acc
  } else {
    if s.byte_at(i) == 120 {
      spec_scan(s, i + 1, target, i + 1)
    } else {
      spec_scan(s, i + 1, target, acc)
    }
  }
}

fn scan_exec(s: &String, i: u64, target: u64, acc: u64) -> u64
  req i <= target && target <= s.len() && acc <= i
  ens result == spec_scan(s, i, target, acc)
  fx  pure
  dec target - i
{
  if i >= target {
    acc
  } else {
    let b: u64 = s.byte_at(i);
    if b == 120 {
      scan_exec(s, i + 1, target, i + 1)
    } else {
      scan_exec(s, i + 1, target, acc)
    }
  }
}

fn use_scan(s: &String) -> u64
  req true
  ens result == spec_scan(s, 0, s.len(), 0)
  fx  pure
{
  scan_exec(s, 0, s.len(), 0)
}
";

#[test]
fn string_scanning_spec_fn_lowers_and_certifies_l3() {
    if !verus_present() {
        eprintln!("SKIP: verus not available — #126(A) spec-fn String-param cert not run.");
        return;
    }
    let certs = check_program("ok", SCAN_PROGRAM);
    // (A): the String-scanning `spec fn` itself lowers (no E0308 from the bare
    // `byte_at`/`len`/`dec` in spec position) and certifies L3 — the proof of the
    // `.with_strings` threading into `lower_spec_fn_body` + `spec_dec`.
    assert_eq!(
        level_of(&certs, "spec_scan"),
        "L3",
        "a String-scanning `spec fn` (byte_at over a &String param) must lower + certify L3:\n{certs:#?}"
    );
    // The exec twin proves `ens result == spec_scan(..)` — the contract NAMES the
    // String-scanning spec fn and discharges (the recursive `(i + 1) as u64` narrowing).
    assert_eq!(
        level_of(&certs, "scan_exec"),
        "L3",
        "the exec twin pinned to `spec_scan` must certify L3:\n{certs:#?}"
    );
    // A fn naming the spec fn in its contract with a `s.len()` argument (the
    // `s.spec_len() as u64` narrowing) certifies L3 — the #126(A) payoff.
    assert_eq!(
        level_of(&certs, "use_scan"),
        "L3",
        "a fn naming the String-scanning spec fn in a contract (with a .len() arg) must certify L3:\n{certs:#?}"
    );
}

#[test]
fn broken_scan_body_rejects_below_l3() {
    if !verus_present() {
        eprintln!("SKIP: verus not available — #126(A) non-vacuity not run.");
        return;
    }
    // Non-vacuity (R-DEFER-9): a mutated exec twin that returns the seed `0`
    // unconditionally no longer equals `spec_scan(s, i, target, acc)` (which counts
    // up to the last newline), so the `ens result == spec_scan(..)` equality FAILS
    // and `scan_exec` rejects BELOW L3. The contract is real, not vacuous.
    let mutant = SCAN_PROGRAM.replace(
        "  if i >= target {\n    acc\n  } else {\n    let b: u64 = s.byte_at(i);",
        "  if i >= target {\n    0\n  } else {\n    let b: u64 = s.byte_at(i);",
    );
    assert_ne!(
        mutant, SCAN_PROGRAM,
        "the mutation must actually change the exec twin's base case (else the test is vacuous)"
    );
    let certs = check_program("broken", &mutant);
    assert_ne!(
        level_of(&certs, "scan_exec"),
        "L3",
        "a broken exec twin (returns the seed `0`) must NOT certify L3 — the \
         `ens result == spec_scan(..)` is non-vacuous:\n{certs:#?}"
    );
}
