//! Divergence pin (#130, residual of #127): the SHAPE-keyed byte-view / generated-
//! def shadow (`fluffy-lower/src/lower.rs` `user_string_spec_fn_names` +
//! `program_uses_parse`/`program_uses_string_search`/`program_uses_numfmt`) only
//! suppresses the generated def-module emission when the SHADOWED NAME is the *only*
//! trigger. When a program BOTH (a) declares a user `spec fn` whose name collides
//! with a generated byte-view fn (e.g. `spec fn is_digit(s: &String, ..)` /
//! `spec fn count_sep(s: &String, ..)`) AND (b) GENUINELY uses the generated module
//! through a DIFFERENT, non-shadowed trigger (`parse_u64(s)` pulls in the parse
//! module which DEFINES `is_digit(b: u8)`; `s.split(sep)` pulls in the C5 search
//! module which DEFINES `count_sep(s, sep)`), the whole-program `fluffy_lower::lower`
//! emits the generated def ALONGSIDE the user def — a DOUBLE DEFINITION (rustc/verus
//! E0428, "the name is defined multiple times"). The lowered Verus source does not
//! compile.
//!
//! AUTHORITY: `.design/basis/07-strings.md` REQ-4 — the byte-view dispatch is
//! SHAPE-derived; a user String-scanning `spec fn` MUST lower + certify L3 and lives
//! in the user namespace, SHADOWING the generated name. A shape-keyed dispatch is
//! collision-free by construction: a generated def whose name a user `spec fn` has
//! claimed must NOT also be materialized. The #127 commit `053190f` states this
//! exact goal in its message ("a user `is_digit` no longer ALSO emits the generated
//! `is_digit` -> E0428 ... so a user-named collision does not emit the generated
//! def"); this test shows that goal is met ONLY when the collided name is the sole
//! trigger, and is VIOLATED when the module is genuinely used via another name.
//! `fluffy-design.md` §3 — Fluffy lowers to (compilable) Rust/Verus source.
//!
//! R-CHAR-3: the expected value (AT MOST ONE definition per name in the lowered
//! source) is the design property (a closed surface with one definition per name,
//! §4.4 / REQ-4's namespace claim), NOT copied from the toolchain's own output. The
//! divergence is the NAME COLLISION, not the generated emission itself.
//!
//! RESOLUTION (#130 fix): the generated byte-view helpers are minted under the
//! RESERVED prefix `__fluffy_` (the toolchain's own namespace, REQ-4 collision-free
//! by construction; `fluffy-spec` forbids a user declaring a `__fluffy_*` name).
//! So `parse_u64(s)` materializes `__fluffy_is_digit(b: u8)` — a name DISTINCT from
//! a user `spec fn is_digit(&String,..)`. The property asserted is therefore: the
//! surface name is defined AT MOST ONCE (the user's, when present), the generated
//! helper is genuinely materialized under its reserved name (exactly once), and NO
//! name is defined twice (no E0428 — the lowered source compiles). The control arm
//! (no user collision) pins that the generated module IS emitted (reserved-named),
//! not silently suppressed.

fn lower_ok(prog: &str) -> String {
    let parsed = fluffy_syntax::parse(prog);
    assert!(
        parsed.errors.is_empty(),
        "parse errors: {:?}",
        parsed.errors
    );
    fluffy_lower::lower(&parsed.program).expect("lower must not hard-error")
}

fn def_count(src: &str, name_decl: &str) -> usize {
    // count source lines that DECLARE a fn `name` (a `fn <name>(` / `spec fn <name>(`
    // signature line) — a definition site, not a call.
    src.lines()
        .filter(|l| {
            let t = l.trim_start();
            (t.contains(&format!("fn {name_decl}(")) || t.contains(&format!("fn {name_decl} ")))
                && (t.starts_with("fn ")
                    || t.starts_with("pub fn ")
                    || t.starts_with("spec fn ")
                    || t.starts_with("pub spec fn ")
                    || t.starts_with("pub open spec fn ")
                    || t.starts_with("open spec fn "))
        })
        .count()
}

// (#130) A user `spec fn is_digit(s: &String, ..)` collides with the GENERATED
// `is_digit(b: u8)` that `parse_u64(s)` (a non-shadowed trigger) materializes. The
// whole-program lowering emits BOTH -> E0428. A correct shape-keyed dispatch yields
// at most one `is_digit` definition.
#[test]
fn user_isdigit_plus_genuine_parse_use_no_double_def() {
    // CONTROL: a NON-colliding user name (`scan`) + the same `parse_u64(s)` use ->
    // exactly one generated `is_digit` def (the divergence is the collision, not the
    // generated emission).
    let control = r#"
spec fn scan(s: &String, i: u64) -> bool
  dec i
{ if i == 0 { true } else { scan(s, i - 1) } }

fn p(s: &String) -> Option<u64>
  req true
  ens true
  fx  pure
{ parse_u64(s) }
"#;
    // CONTROL: the parse module is GENUINELY materialized — but under the RESERVED
    // namespace (#130's fix: `__fluffy_is_digit`, not the bare `is_digit`), so the
    // bare surface name has ZERO defs and the reserved name has exactly one. This
    // pins that the generated emission is present (not silently suppressed) while
    // living in the toolchain's own collision-free namespace (07-strings.md REQ-4).
    let control_src = lower_ok(control);
    assert_eq!(
        def_count(&control_src, "is_digit"),
        0,
        "CONTROL: the generated parse helper is RESERVED-named, so the bare `is_digit` \
         must not appear as a def in a program with no user `is_digit`"
    );
    assert_eq!(
        def_count(&control_src, "__fluffy_is_digit"),
        1,
        "CONTROL: the parse module must be genuinely materialized — exactly one \
         reserved-named `__fluffy_is_digit` def; if this fails the fixture is wrong, \
         not the toolchain"
    );

    // DIVERGENCE: rename the user spec fn to `is_digit` (a name that, pre-#130, the
    // generated parse def claimed). `parse_u64(s)` is an independent, non-shadowed
    // trigger that materializes the parse module. With the RESERVED-name fix the
    // generated helper is `__fluffy_is_digit`, DISTINCT from the user's
    // `is_digit(&String,..)` — so the surface name `is_digit` is defined AT MOST ONCE
    // (the user's), the reserved name once (the generated), and NO name is defined
    // twice (no E0428; the lowered source compiles).
    let collide = control.replace("scan", "is_digit");
    let collide_src = lower_ok(&collide);
    let n = def_count(&collide_src, "is_digit");
    assert!(
        n <= 1,
        "DIVERGENCE (#130): a user `spec fn is_digit(&String,..)` that coexists with a \
         genuine `parse_u64(s)` use must NOT double-define `is_digit` — the SHAPE-keyed \
         dispatch (07-strings.md REQ-4) must be collision-free, but the lowering emitted \
         {n} definitions of `is_digit` (E0428)"
    );
    assert_eq!(
        n, 1,
        "DIVERGENCE (#130): the user `is_digit(&String,..)` def must survive (exactly one)"
    );
    assert_eq!(
        def_count(&collide_src, "__fluffy_is_digit"),
        1,
        "DIVERGENCE (#130): the generated parse helper still materializes under its \
         RESERVED name `__fluffy_is_digit`, distinct from the user's `is_digit`"
    );
}

// (#130) The C5 search analogue: a user `spec fn count_sep(s: &String, ..)` collides
// with the GENERATED `count_sep` that `s.split(sep)` materializes -> E0428.
#[test]
fn user_countsep_plus_genuine_split_use_no_double_def() {
    let control = r#"
spec fn piece(s: &String, i: u64) -> u64
  dec i
{ if i == 0 { 0 } else { piece(s, i - 1) } }

fn p(s: &String) -> Vec<String>
  req true
  ens true
  fx  alloc
{ s.split(44) }
"#;
    let control_src = lower_ok(control);
    assert_eq!(
        def_count(&control_src, "count_sep"),
        0,
        "CONTROL: the generated search helper is RESERVED-named, so bare `count_sep` \
         must not appear as a def in a program with no user `count_sep`"
    );
    assert_eq!(
        def_count(&control_src, "__fluffy_count_sep"),
        1,
        "CONTROL: the search module must be genuinely materialized — exactly one \
         reserved-named `__fluffy_count_sep` def"
    );

    let collide = control.replace("piece", "count_sep");
    let collide_src = lower_ok(&collide);
    let n = def_count(&collide_src, "count_sep");
    assert!(
        n <= 1,
        "DIVERGENCE (#130): a user `spec fn count_sep(&String,..)` that coexists with a \
         genuine `s.split(sep)` use must NOT double-define `count_sep` (07-strings.md \
         REQ-4, collision-free) — the lowering emitted {n} definitions (E0428)"
    );
    assert_eq!(
        n, 1,
        "DIVERGENCE (#130): the user `count_sep(&String,..)` def must survive (exactly one)"
    );
    assert_eq!(
        def_count(&collide_src, "__fluffy_count_sep"),
        1,
        "DIVERGENCE (#130): the generated search helper still materializes under its \
         RESERVED name `__fluffy_count_sep`, distinct from the user's `count_sep`"
    );
}
